apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vlm4ad-pvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
